language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t prsnt1989/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true prsnt1989/react-test npm test -- --coverage

after_success:
  - docker build -t prsnt1989/multi-client ./client
  - docker build -t prsnt1989/multi-nginx ./nginx
  - docker build -t prsnt1989/multi-server ./server
  - docker build -t prsnt1989/multi-worker ./worker
  # Login to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "DOCKER_ID" --password-stdin
  # Take these images and push to docker hub
  - docker push prsnt1989/multi-client
  - docker push prsnt1989/multi-nginx
  - docker push prsnt1989/multi-server
  - docker push prsnt1989/multi-worker


